//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbcourier
    {
        public long iCrSysID { get; set; }
        public Nullable<long> iEmpSysID { get; set; }
        public string sCr_ID { get; set; }
        public Nullable<byte> iAreaID { get; set; }
        public Nullable<byte> iVh_ID { get; set; }
        public Nullable<byte> iInsntive { get; set; }
        public Nullable<byte> iOprShift { get; set; }
    
        public virtual dbtodelarea dbtodelarea { get; set; }
        public virtual dbtovhcl dbtovhcl { get; set; }
        public virtual dbemployee dbemployee { get; set; }
    }
}
