//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbemployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbemployee()
        {
            this.dbcouriers = new HashSet<dbcourier>();
        }
    
        public long iEmpSysID { get; set; }
        public string sEmpAttdID { get; set; }
        public string sEmpCardNumber { get; set; }
        public string sEmpOtherNumber { get; set; }
        public string sEmpName { get; set; }
        public string sEmpGenIdentNum { get; set; }
        public byte iEmpGender { get; set; }
        public byte iEmpMaritalStat { get; set; }
        public byte iEmpReligion { get; set; }
        public byte iEmpLastEdu { get; set; }
        public string sEmpHTown { get; set; }
        public Nullable<System.DateTime> dEmpBirth { get; set; }
        public byte iSmokers { get; set; }
        public string sEmpAddress { get; set; }
        public string sEmpPhone { get; set; }
        public string sEmpHP { get; set; }
        public string sEmpWKPh { get; set; }
        public string sEmpWorkMail { get; set; }
        public string sEmpPersonalMail { get; set; }
        public byte iDept { get; set; }
        public byte iGrade { get; set; }
        public Nullable<byte> iJob { get; set; }
        public int iBldSysID { get; set; }
        public Nullable<int> iRmSysID { get; set; }
        public Nullable<System.DateTime> dEmpJn { get; set; }
        public byte iEmpStat { get; set; }
        public string sPictLink { get; set; }
    
        public virtual dbbuilding dbbuilding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbcourier> dbcouriers { get; set; }
        public virtual dbtogender dbtogender { get; set; }
        public virtual dbempstat dbempstat { get; set; }
        public virtual dbtomaritalstat dbtomaritalstat { get; set; }
        public virtual dbtoreligion dbtoreligion { get; set; }
        public virtual dbtolasteducation dbtolasteducation { get; set; }
        public virtual dbtodept dbtodept { get; set; }
        public virtual dbtojob dbtojob { get; set; }
        public virtual dbtograde dbtograde { get; set; }
        public virtual dbroom dbroom { get; set; }
    }
}
