//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbroom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbroom()
        {
            this.dbemployees = new HashSet<dbemployee>();
        }
    
        public int iRmSysID { get; set; }
        public int iBldSysID { get; set; }
        public string sRmName { get; set; }
        public string sNots { get; set; }
    
        public virtual dbbuilding dbbuilding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbemployee> dbemployees { get; set; }
    }
}
