//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbtoflag
    {
        public byte iFlag { get; set; }
        public string sFlag { get; set; }
    }
}
